exclude = [
    ".git",
    ".devcontainer",
    "__pycache__",
    "build",
    "dist",
]

ignore = [
    "E",
    "W",
    "PLW",
    "RUF001",
    "RUF010", # explicit conversion to string or repr: !s or !r
    "B008", # function call in arg defaults
]

line-length = 88

select = [
    "C90", # McCabe Complexity
    "F", # pyflakes codes
    "I", # isort
    "S", # flake8-bandit
    "B", # flake8-bugbear
    "N", # pep8-naming
    "UP", # pyupgrade
    "PL", # pylint
    "RUF", # ruff
    "SIM", # flake8-simplify
]

fixable = [
    "UP", # e.g. List -> list
    "I", # sort imports
]

target-version = "py39"

[mccabe]
max-complexity = 10

[per-file-ignores]
"scripts/*" = ["PL", "S", "SIM"]
"tests/*" = ["S", "SIM"]
".devcontainer/*" = ["S", "SIM"]
