# This file is only needed, if your repository uses FastAPI
name: Check if openapi.yaml is up to date

on: push

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2

      - id: common
        uses: ghga-de/gh-action-common@v1.0.2

      - name: Check if openapi.yaml is up to date
        run: |
          ./scripts/update_openapi_docs.py --check
