name: Check if the README file is up to date

on: push

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest

    name: Check README file

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4

      - name: Common steps
        id: common
        uses: ghga-de/gh-action-common@v5

      - name: Check README
        id: check-readme
        run: |
          ./scripts/update_readme.py --check
