name: Check if the config schema and the example are up to date.

on: push

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Get/export important runtime variables
        id: runtime_variables
        run: |
          PACKAGE_NAME="$(./scripts/get_package_name.py)"
          MAIN_SRC_DIR="${PWD}/${PACKAGE_NAME}"
          CONFIG_YAML_ENV_VAR_NAME="$( echo ${PACKAGE_NAME^^} | sed "s/-/_/g" )_CONFIG_YAML"
          CONFIG_YAML="${PWD}/.devcontainer/.dev_config.yaml"

          # attach all other variables to the step's output:
          echo "::set-output name=PACKAGE_NAME::${PACKAGE_NAME}"
          echo "::set-output name=MAIN_SRC_DIR::${MAIN_SRC_DIR}"
          echo "::set-output name=CONFIG_YAML_ENV_VAR_NAME::${CONFIG_YAML_ENV_VAR_NAME}"
          echo "::set-output name=CONFIG_YAML::${CONFIG_YAML}"

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          pip install ".[all]"

      - name: Check if config schema is up to date
        run: |
          export ${{ steps.runtime_variables.outputs.CONFIG_YAML_ENV_VAR_NAME }}="${{ steps.runtime_variables.outputs.CONFIG_YAML }}"

          # regenerate config schema:
          ./scripts/get_config_shema_and_example.py print-schema > config_schema_regen.json

          # compare with existing json:
          diff config_schema_regen.json config_schema.json

      - name: Check if config example is up to date
        run: |
          export ${{ steps.runtime_variables.outputs.CONFIG_YAML_ENV_VAR_NAME }}="${{ steps.runtime_variables.outputs.CONFIG_YAML }}"

          # regenerate config schema:
          ./scripts/get_config_shema_and_example.py print-example > example_config_regen.yaml

          # compare with existing yaml:
          diff example_config_regen.yaml example_config.yaml
