name: Continuous Integration Release 

on:
  release:
      types: [published]

jobs:
  push_to_docker_hub:
    uses: ghga/helmfile-templates/.github/workflows/ci-reusable-workflow.yml@add-ci-reusable-workflow
    with:
        tag: ${{ github.event.release.tag_name }}
    secrets: inherit
