name: CI on release

on:
  release:
      types: [published]

jobs:
  push_to_docker_hub:
    uses: ghga-de/gh-action-common/.github/workflows/ci-workflow-call.yml@add-ci-reusable-workflow
    with:
        tag: ${{ github.event.release.tag_name }}
    secrets: inherit
