name: CI on release

on:
  release:
      types: [published]

jobs:
  push_to_docker_hub:
    uses: ghga-de/helmfile-templates/.github/workflows/ci-reusable-workflow.yml@main
    with:
        tag: ${{ github.event.release.tag_name }}
    secrets: inherit
